<?php

namespace Database\Seeders;

use App\Models\Brand;
use Illuminate\Database\Seeder;

class BrandSeeder extends Seeder
{
    public function run(): void
    {
        $brands = [
            'abarth',
            'acura',
            'aiways',
            'alfa romeo',
            'alpine',
            'ariel',
            'aston martin',
            'audi',
            'baic',
            'bentley',
            'bmw',
            'bollore',
            'borgward',
            'brabus',
            'bugatti',
            'buick',
            'byd',
            'cadillac',
            'changan',
            'chery',
            'chevrolet',
            'chrysler',
            'citroen',
            'cupra',
            'dacia',
            'daewoo',
            'daihatsu',
            'datsun',
            'delorean',
            'dodge',
            'dongfeng',
            'ds automobiles',
            'faraday future',
            'ferrari',
            'fiat',
            'fisker',
            'ford',
            'foton',
            'geely',
            'genesis',
            'gmc',
            'great wall',
            'gwm',
            'haval',
            'honda',
            'hongqi',
            'hummer',
            'hyundai',
            'ineos',
            'infiniti',
            'isuzu',
            'jaguar',
            'jeep',
            'jetour',
            'jmc',
            'kia',
            'koenigsegg',
            'lada',
            'lamborghini',
            'lancia',
            'land rover',
            'leapmotor',
            'lexus',
            'li auto',
            'lincoln',
            'lotus',
            'lucid',
            'lynk & co',
            'mahindra',
            'maserati',
            'maybach',
            'mazda',
            'mclaren',
            'mercedes-benz',
            'mercury',
            'mg',
            'mini',
            'mitsubishi',
            'morgan',
            'nio',
            'nissan',
            'oldsmobile',
            'omoda',
            'opel',
            'ora',
            'pagani',
            'perodua',
            'peugeot',
            'polestar',
            'pontiac',
            'porsche',
            'proton',
            'qoros',
            'ram',
            'renault',
            'rimac',
            'rivian',
            'rolls-royce',
            'rover',
            'saab',
            'saturn',
            'scion',
            'seat',
            'seres',
            'skoda',
            'smart',
            'ssangyong',
            'subaru',
            'suzuki',
            'tata',
            'tesla',
            'toyota',
            'vauxhall',
            'vinfast',
            'volkswagen',
            'volvo',
            'wuling',
            'xpeng',
        ];

        $payload = array_map(
            static fn (string $brand): array => ['name' => mb_strtolower(trim($brand))],
            $brands
        );

        Brand::query()->upsert($payload, ['name'], ['name']);
    }
}
