sonar.projectKey=couvoit-api-obidah

sonar.sources=app
sonar.tests=tests

sonar.php.coverage.reportPaths=coverage.xml

sonar.exclusions=vendor/**,storage/**,bootstrap/**,public/**
sonar.coverage.exclusions=**/database/**,**/config/**,**/routes/**,**/tests/**,**/app/Swagger/**
